import PokemonHeader from "@/components/PokemonHeader";
import PokemonListRender from "@/components/PokemonListRender";
import { IHomeProps, IPropsStaticProps } from "@/services/@types";
import { api } from "@/services/api";
import Head from "next/head";
import { useState } from "react";

function Home({ pokemonList }: IHomeProps) {
  const [search, setSearch] = useState<string>("");
  const searchPokemon = pokemonList.filter((findPokemon) => {
    return search === ""
      ? true
      : findPokemon.name.toLowerCase().includes(search.toLowerCase());
  });

  return (
    <>
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./Pokebola.png" />
      </Head>

      <PokemonHeader setSearch={setSearch} />

      <main>
        <PokemonListRender searchPokemon={searchPokemon} />
      </main>
    </>
  );
}

export async function getStaticProps() {
  const { data: pokemonList } = await api.get("pokemon", {
    params: {
      limit: 1050,
      offset: 0,
    },
  });

  pokemonList.results.forEach((item: IPropsStaticProps, index: number) => {
    item.id = index + 1;
  });

  const revalidatingTime = 60 * 60 * 12;

  return {
    props: {
      pokemonList: pokemonList.results,
    },
    revalidate: revalidatingTime,
  };
}
export default Home;
